#!/usr/bin/env bash
# Process and PID file
echo $$ > /var/run/holbertonscript.pid
trap catchsigterm 15
catchsigterm()
{
    echo "I hate the kill command"
    remove
}

trap catchsigint 2
catchsigint()
{
    echo "Y U no love me?!"
}

trap catchsigquit 3
catchsigquit()
{
    remove
}
remove()
{
    rm /var/run/holbertonscript.pid
    exit 0
}
while true
do
    echo "To infinity and beyond"
    sleep 2
done
