#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
hours=0
minutes=1
while ((hours<=12))
do
    echo Hour: $hours
    while ((minutes<=59))
    do
        echo $minutes
        let minutes+=1
    done
    let minutes=1
    let hours+=1
done
